Se resuelve el issue 4
joausaga/cipe pull request #12
Opened 2020-06-03 00:24 UTC by OscarGonzalez97

Aún no borro la parte de Maps, no se si te gustaria que yo haga eso para hacer el merge, ahora deje todo para que puedas comparar y comprobar si falta algo.

2020-06-04 21:49 UTC, joausaga reviewed
Hola Oscar el PR tiene que ser a develop no a master

2020-06-04 21:49 UTC, joausaga commented on app/static/app/js/cipe.js
> +        //aca empezamos la parte de leaflet
borrar este comentario

2020-06-05 09:23 UTC, joausaga reviewed
Terminé de revisar cipe.js y dejé comentarios para solucionar

2020-06-05 09:23 UTC, joausaga commented on app/static/app/js/cipe.js
> +function addMarkers(scientists, isIndex, leafletMap, leafletMarkers) {
Explicar por favor en comentarios al inicio de la funcion que significan las variable **leafletMap** y **leafletMarkers**

2020-06-05 09:23 UTC, joausaga commented on app/static/app/js/cipe.js
> +        var leafletMarker = L.marker([pos.lat,pos.lng]);
Mejor usar **let** en lugar de **var**

2020-06-05 09:23 UTC, joausaga commented on app/static/app/js/cipe.js
> +    //agregamos el cluster de leaflet al mapa
Los comentarios debe ir en inglés

2020-06-05 16:18 UTC, joausaga commented on app/static/app/js/cipe.js
> +function addMarkers(scientists, isIndex, leafletMap, leafletMarkers) {
Cambiar a
```
/***
leafletMap: variable containing the map
leafletMarkers: variable containing the group of markers
***/
```

2020-06-05 16:20 UTC, OscarGonzalez97 commented on app/static/app/js/cipe.js
> +function addMarkers(scientists, isIndex, leafletMap, leafletMarkers) {
Gracias por las correcciones la verdad desconocia de las buenas prácticas de Javascript

2020-06-05 16:36 UTC, OscarGonzalez97 commented on app/static/app/js/cipe.js
> +function addMarkers(scientists, isIndex, leafletMap, leafletMarkers) {
seria dentro de la funcion o afuera? ahora me hace dudar, esta adentro de esa forma ahora pero vi en otros codigos que puede estar afuera

2020-06-08 21:49 UTC, joausaga commented on app/static/app/js/cipe.js
> +function addMarkers(scientists, isIndex, leafletMap, leafletMarkers) {
dento está bien

2020-06-08 22:10 UTC, joausaga requested changes

2020-06-08 22:10 UTC, joausaga commented on app/templates/map.html
> +            <div id="leafletMap"></div>
Por qué no llamarle map como estaba?

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> +    var leafletMap = L.map('leafletMap-registration', {
Esto se repite aquí y en `map.html`, mejor definir una función en `cipe.js` que retorne la configuración del mapa

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> +        document.getElementById("id_location_lat").value = e.location.y; //latitud
Poner comentario en inglés

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> +        document.getElementById("id_location_lng").value = e.location.x; //longitud
Poner comentario en inglés

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> +            addMarker(leafletMap, institution['latitude'], institution['longitude'], institution['name']);
Cambiar a `map`

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> +                            <div id="leafletMap-registration"></div>
Cambiar a `map`

2020-06-08 22:10 UTC, joausaga commented on app/templates/register.html
> -                <input id="pac-input" class="map-search-box" type="text" placeholder="Buscar institución">
Tenemos el mismo placeholder en la barra de búsqueda?

2020-06-08 22:10 UTC, joausaga commented on app/utils.py
> +def get_location_info_from_coordinates_gmaps(latitude, longitude, language='es'):
Elimina nomás, total siempre se puede recuperar yendo atrás en el historia de versionamiento

2020-06-08 22:10 UTC, joausaga commented on app/utils.py
> +            region = jsonResult['address']['state']
Cambiar. Para comprobar si una clave existe en un dictionary la forma "pythonica" de hacerlo es
`if CLAVE in DICTIONARY`.
También comprobar que las claves road, postcode, y city existen. Si por algún motivo el API de OSM cambia y ya no se envian estas claves el código va a fallar.

2020-06-08 22:10 UTC, joausaga commented on app/utils.py
> +def get_location_info_from_name_gmaps(location_name, language='es'):
Eliminar

2020-06-08 22:10 UTC, joausaga commented on app/utils.py
> +    queryFormat=locationName.replace(' ','+')
Utilizar funciones de la librería urllib para formatear el url http://www.compciv.org/guides/python/how-tos/creating-proper-url-query-strings/

2020-06-08 22:10 UTC, joausaga commented on app/utils.py
> +        address = jsonResult[0]['address']['road']
Verificar que las claves existen

2020-06-08 22:10 UTC, joausaga commented on templates/index.html
> +    var leafletMap = L.map('leafletMap', {
Se repite. Mismo comentario de más arriba

2020-06-08 22:10 UTC, joausaga commented on templates/index.html
> +    {% comment %} <div class="container-fluid px-0" >
Si es comentario, eliminar

2020-06-08 22:28 UTC, OscarGonzalez97 commented on app/templates/map.html
> +            <div id="leafletMap"></div>
En un principio estaba dejando el otro mapa para la comparativa, luego en estas correciones finales se me olvido de reemplazar

2020-06-09 02:02 UTC, OscarGonzalez97 commented on app/templates/register.html
> -                <input id="pac-input" class="map-search-box" type="text" placeholder="Buscar institución">
Buscar institucion esta en la barra de busqueda ahora con este nuevo commit

2020-06-09 02:03 UTC, OscarGonzalez97 commented on app/utils.py
> +def get_location_info_from_coordinates_gmaps(latitude, longitude, language='es'):
Si solo era para comparar las versiones para que tengas a mano, ya borro en mi nuevo commit

2020-06-09 02:38 UTC, OscarGonzalez97 commented on app/utils.py
> +    queryFormat=locationName.replace(' ','+')
Buenisimo, ya agrego eso al commit tambien, el formateo correcto para la consulta al url 👌

2020-06-09 03:22 UTC, OscarGonzalez97 commented
Todavia los cambios de `utils.py` citado mas arriba, estaria en el transcurso del dia

2020-06-09 16:33 UTC, joausaga requested changes

2020-06-09 16:33 UTC, joausaga commented on app/utils.py
> +        content = urllib.request.urlopen("https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=" + str(latitude) + "&lon="+str(longitude)).read()
Por seguridad siempre es mejor formatear el url antes de hacer el request

2020-06-09 16:33 UTC, joausaga commented on app/utils.py
> +        address = json_result['address']['road']
Hay que verificar que las claves existan en json_result o sino el código puede fallar

2020-06-09 16:33 UTC, joausaga commented on app/utils.py
> +        address = json_result[0]['address']['road']
Mismo comentario anterior, verificar que las claves existan antes de intentar acceder a ellas

2020-06-10 22:10 UTC, joausaga commented on app/utils.py
> +DICTIONARY= {}
Para que se utiliza este diccionario?

2020-06-12 10:33 UTC, merged