Adds scripts to ease setup/cleanup process
joausaga/cipe pull request #7
Opened 2020-01-24 12:32 UTC by alefq

- Added default credentials to facilitate quick start
- Added `cleanup-containers.sh` to reset the whole process

2020-01-24 13:46 UTC, joausaga requested changes

2020-01-24 13:46 UTC, joausaga commented on README.md
> +6. Generate a random secret key to be used as part of the configuration of the tool. One way of
Este paso ya no haria falta ya que el script `prepare-config-templates.sh` lo hace

2020-01-24 17:10 UTC, alefq commented on README.md
> +6. Generate a random secret key to be used as part of the configuration of the tool. One way of
Listo, removido.

2020-01-25 11:46 UTC, joausaga approved these changes

2020-01-25 11:46 UTC, merged